name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - ".gitignore"
      - ".github/CODEOWNERS"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"
      - ".github/workflows/dependabot-automerge.yaml"

  repository_dispatch:
    types: [dependabot-deploy]

  workflow_dispatch:

  schedule:
    # Deploy den 3. i hver måned kl. 08.31 (så er vi innafor "bygg og deploy minst hver 3. måned"-etterlevelseskravet)
    - cron: "31 8 3 * *"

env:
  TZ: Europe/Oslo

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@main
    with:
      team: oppgjorsrapporter
      build-command: 'pnpm run build && rm -rf node_modules && pnpm install --prod --frozen-lockfile --ignore-scripts --no-optional'
      node-version: '24'
      cdn-source: './dist/client/_astro'
      cdn-destination: 'sokos-oppgjorsrapporter-selvbetjening-frontend'
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-prod:
    needs: [build, deploy-dev]
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-gcp
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
