name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - ".gitignore"
      - ".github/CODEOWNERS"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"
      - ".github/workflows/dependabot-automerge.yaml"

  repository_dispatch:
    types: [dependabot-deploy]

  workflow_dispatch:

  schedule:
    # Deploy den 3. i hver måned kl. 08.31 (så er vi innafor "bygg og deploy minst hver 3. måned"-etterlevelseskravet)
    - cron: "31 8 3 * *"

env:
  TZ: Europe/Oslo

# Hvis denne workflowen trigges flere ganger i løpet av kort tid (f.eks. ved at multiple PRs merges kjapt etter
# hverandre), vil vi at kjøringene [N+1, ...] skal vente med å starte til kjøring N er ferdig.
# På denne måten kan vi være sikre på at dersom N+1 f.eks. inneholder en sikkerhetsfiks, så risikerer vi ikke at N
# bruker lang tid på dev-deploy, og så prod-deployes (uten fiksen) etter N+1.
# Settingen `cancel-in-progress: false` gjør at:
#  * Hvis jobb N+1 trigges mens N fortsatt kjører, blir *ikke* N avbrutt, men N+1 blir liggende i kø til N er ferdig
#  * Hvis jobb N+2 også trigges mens N fortsatt kjøres, fjernes N+1, og N+2 legges i kø
concurrency:
  group: deploy
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@main
    with:
      team: oppgjorsrapporter
      build-command: 'pnpm run build && rm -rf node_modules && pnpm install --prod --frozen-lockfile --ignore-scripts --no-optional'
      node-version: '24'
      cdn-source: './dist/client/_astro'
      cdn-destination: 'sokos-oppgjorsrapporter-selvbetjening-frontend'
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-prod:
    needs: [build, deploy-dev]
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-gcp
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
